version: '3.9'
services:
  mongo:
    image: mongo:7
    container_name: bin-saleem-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: bin-saleem-jewellery
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
