// Single red placeholder image used everywhere a product/category/item image
// is missing, so the same fallback is shown in every table/card and, when
// used as the default payload value, ends up persisted in the backend too.
export const NO_IMAGE_PLACEHOLDER =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiB2aWV3Qm94PSIwIDAgMTAwIDEwMCI+PHJlY3Qgd2lkdGg9IjEwMCIgaGVpZ2h0PSIxMDAiIGZpbGw9IiNkYzI2MjYiLz48cGF0aCBkPSJNMjggMzNoNDRhNSA1IDAgMDE1IDV2MjRhNSA1IDAgMDEtNSA1SDI4YTUgNSAwIDAxLTUtNVYzOGE1IDUgMCAwMTUtNXoiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI2ZmZmZmZiIgc3Ryb2tlLXdpZHRoPSIzLjUiLz48Y2lyY2xlIGN4PSIzOSIgY3k9IjQ2IiByPSI0LjUiIGZpbGw9IiNmZmZmZmYiLz48cGF0aCBkPSJNMjUgNjFsMTYtMTMgMTEgOSA5LTcgMTQgMTEiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI2ZmZmZmZiIgc3Ryb2tlLXdpZHRoPSIzLjUiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIvPjwvc3ZnPgo=";
